2024-04-05 00:21:07,685 INFO    StreamThr :17468 [internal.py:wandb_internal():86] W&B internal server running at pid: 17468, started at: 2024-04-05 00:21:07.685518
2024-04-05 00:21:07,686 DEBUG   HandlerThread:17468 [handler.py:handle_request():146] handle_request: status
2024-04-05 00:21:07,692 INFO    WriterThread:17468 [datastore.py:open_for_write():85] open: S:\Cryp-Tor\wandb\run-20240405_002107-qdib93hc\run-qdib93hc.wandb
2024-04-05 00:21:07,692 DEBUG   SenderThread:17468 [sender.py:send():382] send: header
2024-04-05 00:21:07,747 DEBUG   SenderThread:17468 [sender.py:send():382] send: run
2024-04-05 00:21:08,372 INFO    SenderThread:17468 [dir_watcher.py:__init__():211] watching files in: S:\Cryp-Tor\wandb\run-20240405_002107-qdib93hc\files
2024-04-05 00:21:08,385 INFO    SenderThread:17468 [sender.py:_start_run_threads():1136] run started: qdib93hc with start time 1712269267.686515
2024-04-05 00:21:08,385 DEBUG   HandlerThread:17468 [handler.py:handle_request():146] handle_request: check_version
2024-04-05 00:21:08,385 DEBUG   SenderThread:17468 [sender.py:send_request():409] send_request: check_version
2024-04-05 00:21:08,748 DEBUG   HandlerThread:17468 [handler.py:handle_request():146] handle_request: run_start
2024-04-05 00:21:08,774 DEBUG   HandlerThread:17468 [system_info.py:__init__():32] System info init
2024-04-05 00:21:08,774 DEBUG   HandlerThread:17468 [system_info.py:__init__():47] System info init done
2024-04-05 00:21:08,774 INFO    HandlerThread:17468 [system_monitor.py:start():194] Starting system monitor
2024-04-05 00:21:08,774 INFO    SystemMonitor:17468 [system_monitor.py:_start():158] Starting system asset monitoring threads
2024-04-05 00:21:08,774 INFO    HandlerThread:17468 [system_monitor.py:probe():214] Collecting system info
2024-04-05 00:21:08,774 INFO    SystemMonitor:17468 [interfaces.py:start():190] Started cpu monitoring
2024-04-05 00:21:08,774 INFO    SystemMonitor:17468 [interfaces.py:start():190] Started disk monitoring
2024-04-05 00:21:08,774 INFO    SystemMonitor:17468 [interfaces.py:start():190] Started gpu monitoring
2024-04-05 00:21:08,774 INFO    SystemMonitor:17468 [interfaces.py:start():190] Started memory monitoring
2024-04-05 00:21:08,787 INFO    SystemMonitor:17468 [interfaces.py:start():190] Started network monitoring
2024-04-05 00:21:08,787 DEBUG   HandlerThread:17468 [system_info.py:probe():196] Probing system
2024-04-05 00:21:08,787 DEBUG   HandlerThread:17468 [system_info.py:_probe_git():181] Probing git
2024-04-05 00:21:08,845 DEBUG   HandlerThread:17468 [system_info.py:_probe_git():189] Probing git done
2024-04-05 00:21:08,845 DEBUG   HandlerThread:17468 [system_info.py:probe():244] Probing system done
2024-04-05 00:21:08,845 DEBUG   HandlerThread:17468 [system_monitor.py:probe():223] {'os': 'Windows-10-10.0.19045-SP0', 'python': '3.11.5', 'heartbeatAt': '2024-04-04T22:21:08.787807', 'startedAt': '2024-04-04T22:21:07.677407', 'docker': None, 'cuda': None, 'args': (), 'state': 'running', 'program': 'S:\\Cryp-Tor\\CryptoTransformer.py', 'codePathLocal': 'CryptoTransformer.py', 'codePath': 'CryptoTransformer.py', 'git': {'remote': 'https://github.com/Mateo-drr/Cryp-Tor.git', 'commit': '1adc8a5e4fcd3bc7f89e7c68db87e7811b9fb492'}, 'email': 'mateodrr@gmail.com', 'root': 'S:/Cryp-Tor', 'host': 'DESKTOP-24KBHOO', 'username': 'Mateo-drr', 'executable': 'C:\\Users\\Mateo-drr\\AppData\\Local\\miniconda3\\python.exe', 'cpu_count': 4, 'cpu_count_logical': 8, 'cpu_freq': {'current': 3300.0, 'min': 0.0, 'max': 3300.0}, 'cpu_freq_per_core': [{'current': 3300.0, 'min': 0.0, 'max': 3300.0}], 'disk': {'/': {'total': 465.75976181030273, 'used': 32.49551773071289}}, 'gpu': 'NVIDIA GeForce RTX 2060', 'gpu_count': 1, 'gpu_devices': [{'name': 'NVIDIA GeForce RTX 2060', 'memory_total': 12884901888}], 'memory': {'total': 15.828716278076172}}
2024-04-05 00:21:08,845 INFO    HandlerThread:17468 [system_monitor.py:probe():224] Finished collecting system info
2024-04-05 00:21:08,845 INFO    HandlerThread:17468 [system_monitor.py:probe():227] Publishing system info
2024-04-05 00:21:08,845 DEBUG   HandlerThread:17468 [system_info.py:_save_pip():52] Saving list of pip packages installed into the current environment
2024-04-05 00:21:08,845 DEBUG   HandlerThread:17468 [system_info.py:_save_pip():68] Saving pip packages done
2024-04-05 00:21:08,845 DEBUG   HandlerThread:17468 [system_info.py:_save_conda():75] Saving list of conda packages installed into the current environment
2024-04-05 00:21:09,385 INFO    Thread-16 :17468 [dir_watcher.py:_on_file_created():271] file/dir created: S:\Cryp-Tor\wandb\run-20240405_002107-qdib93hc\files\requirements.txt
2024-04-05 00:21:09,385 INFO    Thread-16 :17468 [dir_watcher.py:_on_file_created():271] file/dir created: S:\Cryp-Tor\wandb\run-20240405_002107-qdib93hc\files\conda-environment.yaml
2024-04-05 00:21:12,085 DEBUG   HandlerThread:17468 [system_info.py:_save_conda():87] Saving conda packages done
2024-04-05 00:21:12,085 INFO    HandlerThread:17468 [system_monitor.py:probe():229] Finished publishing system info
2024-04-05 00:21:12,085 DEBUG   SenderThread:17468 [sender.py:send():382] send: files
2024-04-05 00:21:12,085 INFO    SenderThread:17468 [sender.py:_save_file():1392] saving file wandb-metadata.json with policy now
2024-04-05 00:21:12,102 DEBUG   HandlerThread:17468 [handler.py:handle_request():146] handle_request: stop_status
2024-04-05 00:21:12,102 DEBUG   HandlerThread:17468 [handler.py:handle_request():146] handle_request: internal_messages
2024-04-05 00:21:12,103 DEBUG   SenderThread:17468 [sender.py:send_request():409] send_request: stop_status
2024-04-05 00:21:12,411 INFO    Thread-16 :17468 [dir_watcher.py:_on_file_modified():288] file/dir modified: S:\Cryp-Tor\wandb\run-20240405_002107-qdib93hc\files\conda-environment.yaml
2024-04-05 00:21:12,411 INFO    Thread-16 :17468 [dir_watcher.py:_on_file_created():271] file/dir created: S:\Cryp-Tor\wandb\run-20240405_002107-qdib93hc\files\wandb-metadata.json
2024-04-05 00:21:12,578 DEBUG   SenderThread:17468 [sender.py:send():382] send: telemetry
2024-04-05 00:21:12,856 INFO    wandb-upload_0:17468 [upload_job.py:push():131] Uploaded file C:\Users\MATEO-~1\AppData\Local\Temp\tmpeoublx14wandb\oswktkcb-wandb-metadata.json
2024-04-05 00:21:13,579 DEBUG   HandlerThread:17468 [handler.py:handle_request():146] handle_request: status_report
2024-04-05 00:21:18,474 INFO    Thread-16 :17468 [dir_watcher.py:_on_file_created():271] file/dir created: S:\Cryp-Tor\wandb\run-20240405_002107-qdib93hc\files\output.log
2024-04-05 00:21:18,591 DEBUG   HandlerThread:17468 [handler.py:handle_request():146] handle_request: status_report
2024-04-05 00:21:20,485 INFO    Thread-16 :17468 [dir_watcher.py:_on_file_modified():288] file/dir modified: S:\Cryp-Tor\wandb\run-20240405_002107-qdib93hc\files\output.log
2024-04-05 00:21:23,630 DEBUG   HandlerThread:17468 [handler.py:handle_request():146] handle_request: status_report
2024-04-05 00:21:27,098 DEBUG   HandlerThread:17468 [handler.py:handle_request():146] handle_request: stop_status
2024-04-05 00:21:27,098 DEBUG   SenderThread:17468 [sender.py:send_request():409] send_request: stop_status
2024-04-05 00:21:27,110 DEBUG   HandlerThread:17468 [handler.py:handle_request():146] handle_request: internal_messages
2024-04-05 00:21:29,310 DEBUG   HandlerThread:17468 [handler.py:handle_request():146] handle_request: status_report
2024-04-05 00:21:34,345 DEBUG   HandlerThread:17468 [handler.py:handle_request():146] handle_request: status_report
2024-04-05 00:21:39,237 DEBUG   SenderThread:17468 [sender.py:send():382] send: exit
2024-04-05 00:21:39,237 INFO    SenderThread:17468 [sender.py:send_exit():589] handling exit code: 255
2024-04-05 00:21:39,237 INFO    SenderThread:17468 [sender.py:send_exit():591] handling runtime: 30
2024-04-05 00:21:39,237 INFO    SenderThread:17468 [sender.py:_save_file():1392] saving file wandb-summary.json with policy end
2024-04-05 00:21:39,237 INFO    SenderThread:17468 [sender.py:send_exit():597] send defer
2024-04-05 00:21:39,237 DEBUG   HandlerThread:17468 [handler.py:handle_request():146] handle_request: defer
2024-04-05 00:21:39,237 INFO    HandlerThread:17468 [handler.py:handle_request_defer():172] handle defer: 0
2024-04-05 00:21:39,237 DEBUG   SenderThread:17468 [sender.py:send_request():409] send_request: defer
2024-04-05 00:21:39,237 INFO    SenderThread:17468 [sender.py:send_request_defer():613] handle sender defer: 0
2024-04-05 00:21:39,237 INFO    SenderThread:17468 [sender.py:transition_state():617] send defer: 1
2024-04-05 00:21:39,237 DEBUG   HandlerThread:17468 [handler.py:handle_request():146] handle_request: defer
2024-04-05 00:21:39,237 INFO    HandlerThread:17468 [handler.py:handle_request_defer():172] handle defer: 1
2024-04-05 00:21:39,237 DEBUG   SenderThread:17468 [sender.py:send_request():409] send_request: defer
2024-04-05 00:21:39,237 INFO    SenderThread:17468 [sender.py:send_request_defer():613] handle sender defer: 1
2024-04-05 00:21:39,237 INFO    SenderThread:17468 [sender.py:transition_state():617] send defer: 2
2024-04-05 00:21:39,237 DEBUG   HandlerThread:17468 [handler.py:handle_request():146] handle_request: defer
2024-04-05 00:21:39,237 INFO    HandlerThread:17468 [handler.py:handle_request_defer():172] handle defer: 2
2024-04-05 00:21:39,237 INFO    HandlerThread:17468 [system_monitor.py:finish():203] Stopping system monitor
2024-04-05 00:21:39,237 DEBUG   SystemMonitor:17468 [system_monitor.py:_start():172] Starting system metrics aggregation loop
2024-04-05 00:21:39,237 DEBUG   SystemMonitor:17468 [system_monitor.py:_start():179] Finished system metrics aggregation loop
2024-04-05 00:21:39,237 INFO    HandlerThread:17468 [interfaces.py:finish():202] Joined cpu monitor
2024-04-05 00:21:39,237 DEBUG   SystemMonitor:17468 [system_monitor.py:_start():183] Publishing last batch of metrics
2024-04-05 00:21:39,237 INFO    HandlerThread:17468 [interfaces.py:finish():202] Joined disk monitor
2024-04-05 00:21:39,269 INFO    HandlerThread:17468 [interfaces.py:finish():202] Joined gpu monitor
2024-04-05 00:21:39,269 INFO    HandlerThread:17468 [interfaces.py:finish():202] Joined memory monitor
2024-04-05 00:21:39,269 INFO    HandlerThread:17468 [interfaces.py:finish():202] Joined network monitor
2024-04-05 00:21:39,269 DEBUG   SenderThread:17468 [sender.py:send_request():409] send_request: defer
2024-04-05 00:21:39,269 INFO    SenderThread:17468 [sender.py:send_request_defer():613] handle sender defer: 2
2024-04-05 00:21:39,269 INFO    SenderThread:17468 [sender.py:transition_state():617] send defer: 3
2024-04-05 00:21:39,269 DEBUG   SenderThread:17468 [sender.py:send():382] send: stats
2024-04-05 00:21:39,269 DEBUG   HandlerThread:17468 [handler.py:handle_request():146] handle_request: defer
2024-04-05 00:21:39,269 INFO    HandlerThread:17468 [handler.py:handle_request_defer():172] handle defer: 3
2024-04-05 00:21:39,269 DEBUG   SenderThread:17468 [sender.py:send_request():409] send_request: defer
2024-04-05 00:21:39,269 INFO    SenderThread:17468 [sender.py:send_request_defer():613] handle sender defer: 3
2024-04-05 00:21:39,269 INFO    SenderThread:17468 [sender.py:transition_state():617] send defer: 4
2024-04-05 00:21:39,269 DEBUG   HandlerThread:17468 [handler.py:handle_request():146] handle_request: defer
2024-04-05 00:21:39,269 INFO    HandlerThread:17468 [handler.py:handle_request_defer():172] handle defer: 4
2024-04-05 00:21:39,269 DEBUG   SenderThread:17468 [sender.py:send_request():409] send_request: defer
2024-04-05 00:21:39,269 INFO    SenderThread:17468 [sender.py:send_request_defer():613] handle sender defer: 4
2024-04-05 00:21:39,269 INFO    SenderThread:17468 [sender.py:transition_state():617] send defer: 5
2024-04-05 00:21:39,269 DEBUG   HandlerThread:17468 [handler.py:handle_request():146] handle_request: defer
2024-04-05 00:21:39,269 INFO    HandlerThread:17468 [handler.py:handle_request_defer():172] handle defer: 5
2024-04-05 00:21:39,269 DEBUG   SenderThread:17468 [sender.py:send():382] send: summary
2024-04-05 00:21:39,269 INFO    SenderThread:17468 [sender.py:_save_file():1392] saving file wandb-summary.json with policy end
2024-04-05 00:21:39,269 DEBUG   SenderThread:17468 [sender.py:send_request():409] send_request: defer
2024-04-05 00:21:39,269 INFO    SenderThread:17468 [sender.py:send_request_defer():613] handle sender defer: 5
2024-04-05 00:21:39,269 INFO    SenderThread:17468 [sender.py:transition_state():617] send defer: 6
2024-04-05 00:21:39,269 DEBUG   HandlerThread:17468 [handler.py:handle_request():146] handle_request: defer
2024-04-05 00:21:39,269 INFO    HandlerThread:17468 [handler.py:handle_request_defer():172] handle defer: 6
2024-04-05 00:21:39,269 DEBUG   SenderThread:17468 [sender.py:send_request():409] send_request: defer
2024-04-05 00:21:39,269 INFO    SenderThread:17468 [sender.py:send_request_defer():613] handle sender defer: 6
2024-04-05 00:21:39,269 DEBUG   HandlerThread:17468 [handler.py:handle_request():146] handle_request: status_report
2024-04-05 00:21:39,441 INFO    SenderThread:17468 [sender.py:transition_state():617] send defer: 7
2024-04-05 00:21:39,441 DEBUG   HandlerThread:17468 [handler.py:handle_request():146] handle_request: defer
2024-04-05 00:21:39,441 INFO    HandlerThread:17468 [handler.py:handle_request_defer():172] handle defer: 7
2024-04-05 00:21:39,441 DEBUG   SenderThread:17468 [sender.py:send_request():409] send_request: defer
2024-04-05 00:21:39,441 INFO    SenderThread:17468 [sender.py:send_request_defer():613] handle sender defer: 7
2024-04-05 00:21:39,640 INFO    Thread-16 :17468 [dir_watcher.py:_on_file_modified():288] file/dir modified: S:\Cryp-Tor\wandb\run-20240405_002107-qdib93hc\files\config.yaml
2024-04-05 00:21:39,640 INFO    Thread-16 :17468 [dir_watcher.py:_on_file_created():271] file/dir created: S:\Cryp-Tor\wandb\run-20240405_002107-qdib93hc\files\wandb-summary.json
2024-04-05 00:21:40,257 DEBUG   HandlerThread:17468 [handler.py:handle_request():146] handle_request: poll_exit
2024-04-05 00:21:41,242 INFO    SenderThread:17468 [sender.py:transition_state():617] send defer: 8
2024-04-05 00:21:41,242 DEBUG   SenderThread:17468 [sender.py:send_request():409] send_request: poll_exit
2024-04-05 00:21:41,242 DEBUG   HandlerThread:17468 [handler.py:handle_request():146] handle_request: defer
2024-04-05 00:21:41,242 INFO    HandlerThread:17468 [handler.py:handle_request_defer():172] handle defer: 8
2024-04-05 00:21:41,242 DEBUG   SenderThread:17468 [sender.py:send_request():409] send_request: defer
2024-04-05 00:21:41,242 INFO    SenderThread:17468 [sender.py:send_request_defer():613] handle sender defer: 8
2024-04-05 00:21:41,242 INFO    SenderThread:17468 [job_builder.py:build():298] Attempting to build job artifact
2024-04-05 00:21:41,242 INFO    SenderThread:17468 [job_builder.py:_get_source_type():428] is repo sourced job
2024-04-05 00:21:41,257 DEBUG   HandlerThread:17468 [handler.py:handle_request():146] handle_request: poll_exit
2024-04-05 00:21:41,273 INFO    SenderThread:17468 [job_builder.py:build():404] adding wandb-job metadata file
2024-04-05 00:21:41,281 INFO    SenderThread:17468 [sender.py:transition_state():617] send defer: 9
2024-04-05 00:21:41,281 DEBUG   SenderThread:17468 [sender.py:send_request():409] send_request: poll_exit
2024-04-05 00:21:41,281 DEBUG   HandlerThread:17468 [handler.py:handle_request():146] handle_request: defer
2024-04-05 00:21:41,281 DEBUG   SenderThread:17468 [sender.py:send():382] send: artifact
2024-04-05 00:21:41,281 INFO    HandlerThread:17468 [handler.py:handle_request_defer():172] handle defer: 9
2024-04-05 00:21:41,667 INFO    Thread-16 :17468 [dir_watcher.py:_on_file_modified():288] file/dir modified: S:\Cryp-Tor\wandb\run-20240405_002107-qdib93hc\files\output.log
2024-04-05 00:21:42,265 DEBUG   HandlerThread:17468 [handler.py:handle_request():146] handle_request: poll_exit
2024-04-05 00:21:42,447 INFO    wandb-upload_0:17468 [upload_job.py:push():86] Skipped uploading C:\Users\Mateo-drr\AppData\Local\wandb\wandb\artifacts\staging\tmpx2lxu6s4
2024-04-05 00:21:42,919 INFO    wandb-upload_1:17468 [upload_job.py:push():89] Uploaded file C:\Users\Mateo-drr\AppData\Local\wandb\wandb\artifacts\staging\tmp1gisvgzz
2024-04-05 00:21:43,918 INFO    SenderThread:17468 [sender.py:send_artifact():1470] sent artifact job-https___github.com_Mateo-drr_Cryp-Tor.git_CryptoTransformer.py - {'id': 'QXJ0aWZhY3Q6NzgzMDU1NTgy', 'state': 'PENDING', 'artifactSequence': {'id': 'QXJ0aWZhY3RDb2xsZWN0aW9uOjE1NjQ5NzY0Nw==', 'latestArtifact': {'id': 'QXJ0aWZhY3Q6NzgyOTY4Mjg1', 'versionIndex': 0}}}
2024-04-05 00:21:43,918 DEBUG   SenderThread:17468 [sender.py:send_request():409] send_request: defer
2024-04-05 00:21:43,918 INFO    SenderThread:17468 [sender.py:send_request_defer():613] handle sender defer: 9
2024-04-05 00:21:43,918 INFO    SenderThread:17468 [dir_watcher.py:finish():358] shutting down directory watcher
2024-04-05 00:21:44,696 INFO    SenderThread:17468 [dir_watcher.py:finish():388] scan: S:\Cryp-Tor\wandb\run-20240405_002107-qdib93hc\files
2024-04-05 00:21:44,696 INFO    SenderThread:17468 [dir_watcher.py:finish():402] scan save: S:\Cryp-Tor\wandb\run-20240405_002107-qdib93hc\files\conda-environment.yaml conda-environment.yaml
2024-04-05 00:21:44,697 INFO    SenderThread:17468 [dir_watcher.py:finish():402] scan save: S:\Cryp-Tor\wandb\run-20240405_002107-qdib93hc\files\config.yaml config.yaml
2024-04-05 00:21:44,698 INFO    SenderThread:17468 [dir_watcher.py:finish():402] scan save: S:\Cryp-Tor\wandb\run-20240405_002107-qdib93hc\files\output.log output.log
2024-04-05 00:21:44,699 INFO    SenderThread:17468 [dir_watcher.py:finish():402] scan save: S:\Cryp-Tor\wandb\run-20240405_002107-qdib93hc\files\requirements.txt requirements.txt
2024-04-05 00:21:44,700 INFO    SenderThread:17468 [dir_watcher.py:finish():402] scan save: S:\Cryp-Tor\wandb\run-20240405_002107-qdib93hc\files\wandb-metadata.json wandb-metadata.json
2024-04-05 00:21:44,700 INFO    SenderThread:17468 [dir_watcher.py:finish():402] scan save: S:\Cryp-Tor\wandb\run-20240405_002107-qdib93hc\files\wandb-summary.json wandb-summary.json
2024-04-05 00:21:44,702 INFO    SenderThread:17468 [sender.py:transition_state():617] send defer: 10
2024-04-05 00:21:44,702 DEBUG   SenderThread:17468 [sender.py:send_request():409] send_request: poll_exit
2024-04-05 00:21:44,702 DEBUG   HandlerThread:17468 [handler.py:handle_request():146] handle_request: defer
2024-04-05 00:21:44,702 INFO    HandlerThread:17468 [handler.py:handle_request_defer():172] handle defer: 10
2024-04-05 00:21:44,702 DEBUG   HandlerThread:17468 [handler.py:handle_request():146] handle_request: status_report
2024-04-05 00:21:44,703 DEBUG   SenderThread:17468 [sender.py:send_request():409] send_request: defer
2024-04-05 00:21:44,703 INFO    SenderThread:17468 [sender.py:send_request_defer():613] handle sender defer: 10
2024-04-05 00:21:44,703 INFO    SenderThread:17468 [file_pusher.py:finish():175] shutting down file pusher
2024-04-05 00:21:45,114 INFO    wandb-upload_0:17468 [upload_job.py:push():131] Uploaded file S:\Cryp-Tor\wandb\run-20240405_002107-qdib93hc\files\conda-environment.yaml
2024-04-05 00:21:45,300 ERROR   wandb-upload_4:17468 [internal_api.py:execute():373] 404 response executing GraphQL.
2024-04-05 00:21:45,300 ERROR   wandb-upload_4:17468 [internal_api.py:execute():374] {"errors":[{"message":"run Cryp-Tor/qdib93hc not found during createRunFiles","path":["createRunFiles"]}],"data":{"createRunFiles":null}}
2024-04-05 00:21:45,300 ERROR   Thread-15 (_thread_body):17468 [step_upload.py:_handle_event():200] Failed to upload file: S:\Cryp-Tor\wandb\run-20240405_002107-qdib93hc\files\wandb-summary.json
Traceback (most recent call last):
  File "C:\Users\Mateo-drr\AppData\Local\miniconda3\Lib\site-packages\wandb\sdk\lib\retry.py", line 131, in __call__
    result = self._call_fn(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Mateo-drr\AppData\Local\miniconda3\Lib\site-packages\wandb\sdk\internal\internal_api.py", line 369, in execute
    return self.client.execute(*args, **kwargs)  # type: ignore
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Mateo-drr\AppData\Local\miniconda3\Lib\site-packages\wandb\vendor\gql-0.2.0\wandb_gql\client.py", line 52, in execute
    result = self._get_result(document, *args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Mateo-drr\AppData\Local\miniconda3\Lib\site-packages\wandb\vendor\gql-0.2.0\wandb_gql\client.py", line 60, in _get_result
    return self.transport.execute(document, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Mateo-drr\AppData\Local\miniconda3\Lib\site-packages\wandb\sdk\lib\gql_request.py", line 59, in execute
    request.raise_for_status()
  File "C:\Users\Mateo-drr\AppData\Local\miniconda3\Lib\site-packages\requests\models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://api.wandb.ai/graphql

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Mateo-drr\AppData\Local\miniconda3\Lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Mateo-drr\AppData\Local\miniconda3\Lib\site-packages\wandb\filesync\step_upload.py", line 288, in run_and_notify
    self._do_upload_sync(event)
  File "C:\Users\Mateo-drr\AppData\Local\miniconda3\Lib\site-packages\wandb\filesync\step_upload.py", line 330, in _do_upload_sync
    job.run()
  File "C:\Users\Mateo-drr\AppData\Local\miniconda3\Lib\site-packages\wandb\filesync\upload_job.py", line 57, in run
    self.push()
  File "C:\Users\Mateo-drr\AppData\Local\miniconda3\Lib\site-packages\wandb\filesync\upload_job.py", line 106, in push
    _, upload_headers, result = self._api.upload_urls(project, [self.save_name])
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Mateo-drr\AppData\Local\miniconda3\Lib\site-packages\wandb\apis\normalize.py", line 73, in wrapper
    raise err
  File "C:\Users\Mateo-drr\AppData\Local\miniconda3\Lib\site-packages\wandb\apis\normalize.py", line 41, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Mateo-drr\AppData\Local\miniconda3\Lib\site-packages\wandb\sdk\internal\internal_api.py", line 2380, in upload_urls
    query_result = self.gql(
                   ^^^^^^^^^
  File "C:\Users\Mateo-drr\AppData\Local\miniconda3\Lib\site-packages\wandb\sdk\internal\internal_api.py", line 341, in gql
    ret = self._retry_gql(
          ^^^^^^^^^^^^^^^^
  File "C:\Users\Mateo-drr\AppData\Local\miniconda3\Lib\site-packages\wandb\sdk\lib\retry.py", line 147, in __call__
    retry_timedelta_triggered = check_retry_fn(e)
                                ^^^^^^^^^^^^^^^^^
  File "C:\Users\Mateo-drr\AppData\Local\miniconda3\Lib\site-packages\wandb\util.py", line 907, in no_retry_auth
    raise CommError(
wandb.errors.CommError: It appears that you do not have permission to access the requested resource. Please reach out to the project owner to grant you access. If you have the correct permissions, verify that there are no issues with your networking setup.(Error 404: Not Found)
2024-04-05 00:21:45,304 ERROR   wandb-upload_2:17468 [internal_api.py:execute():373] 404 response executing GraphQL.
2024-04-05 00:21:45,310 ERROR   wandb-upload_3:17468 [internal_api.py:execute():373] 404 response executing GraphQL.
2024-04-05 00:21:45,358 ERROR   wandb-upload_2:17468 [internal_api.py:execute():374] {"errors":[{"message":"run Cryp-Tor/qdib93hc not found during createRunFiles","path":["createRunFiles"]}],"data":{"createRunFiles":null}}
2024-04-05 00:21:45,358 ERROR   wandb-upload_3:17468 [internal_api.py:execute():374] {"errors":[{"message":"run Cryp-Tor/qdib93hc not found during createRunFiles","path":["createRunFiles"]}],"data":{"createRunFiles":null}}
2024-04-05 00:21:45,358 ERROR   Thread-15 (_thread_body):17468 [step_upload.py:_handle_event():200] Failed to upload file: S:\Cryp-Tor\wandb\run-20240405_002107-qdib93hc\files\output.log
Traceback (most recent call last):
  File "C:\Users\Mateo-drr\AppData\Local\miniconda3\Lib\site-packages\wandb\sdk\lib\retry.py", line 131, in __call__
    result = self._call_fn(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Mateo-drr\AppData\Local\miniconda3\Lib\site-packages\wandb\sdk\internal\internal_api.py", line 369, in execute
    return self.client.execute(*args, **kwargs)  # type: ignore
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Mateo-drr\AppData\Local\miniconda3\Lib\site-packages\wandb\vendor\gql-0.2.0\wandb_gql\client.py", line 52, in execute
    result = self._get_result(document, *args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Mateo-drr\AppData\Local\miniconda3\Lib\site-packages\wandb\vendor\gql-0.2.0\wandb_gql\client.py", line 60, in _get_result
    return self.transport.execute(document, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Mateo-drr\AppData\Local\miniconda3\Lib\site-packages\wandb\sdk\lib\gql_request.py", line 59, in execute
    request.raise_for_status()
  File "C:\Users\Mateo-drr\AppData\Local\miniconda3\Lib\site-packages\requests\models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://api.wandb.ai/graphql

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Mateo-drr\AppData\Local\miniconda3\Lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Mateo-drr\AppData\Local\miniconda3\Lib\site-packages\wandb\filesync\step_upload.py", line 288, in run_and_notify
    self._do_upload_sync(event)
  File "C:\Users\Mateo-drr\AppData\Local\miniconda3\Lib\site-packages\wandb\filesync\step_upload.py", line 330, in _do_upload_sync
    job.run()
  File "C:\Users\Mateo-drr\AppData\Local\miniconda3\Lib\site-packages\wandb\filesync\upload_job.py", line 57, in run
    self.push()
  File "C:\Users\Mateo-drr\AppData\Local\miniconda3\Lib\site-packages\wandb\filesync\upload_job.py", line 106, in push
    _, upload_headers, result = self._api.upload_urls(project, [self.save_name])
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Mateo-drr\AppData\Local\miniconda3\Lib\site-packages\wandb\apis\normalize.py", line 73, in wrapper
    raise err
  File "C:\Users\Mateo-drr\AppData\Local\miniconda3\Lib\site-packages\wandb\apis\normalize.py", line 41, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Mateo-drr\AppData\Local\miniconda3\Lib\site-packages\wandb\sdk\internal\internal_api.py", line 2380, in upload_urls
    query_result = self.gql(
                   ^^^^^^^^^
  File "C:\Users\Mateo-drr\AppData\Local\miniconda3\Lib\site-packages\wandb\sdk\internal\internal_api.py", line 341, in gql
    ret = self._retry_gql(
          ^^^^^^^^^^^^^^^^
  File "C:\Users\Mateo-drr\AppData\Local\miniconda3\Lib\site-packages\wandb\sdk\lib\retry.py", line 147, in __call__
    retry_timedelta_triggered = check_retry_fn(e)
                                ^^^^^^^^^^^^^^^^^
  File "C:\Users\Mateo-drr\AppData\Local\miniconda3\Lib\site-packages\wandb\util.py", line 907, in no_retry_auth
    raise CommError(
wandb.errors.CommError: It appears that you do not have permission to access the requested resource. Please reach out to the project owner to grant you access. If you have the correct permissions, verify that there are no issues with your networking setup.(Error 404: Not Found)
2024-04-05 00:21:45,358 ERROR   Thread-15 (_thread_body):17468 [step_upload.py:_handle_event():200] Failed to upload file: S:\Cryp-Tor\wandb\run-20240405_002107-qdib93hc\files\requirements.txt
Traceback (most recent call last):
  File "C:\Users\Mateo-drr\AppData\Local\miniconda3\Lib\site-packages\wandb\sdk\lib\retry.py", line 131, in __call__
    result = self._call_fn(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Mateo-drr\AppData\Local\miniconda3\Lib\site-packages\wandb\sdk\internal\internal_api.py", line 369, in execute
    return self.client.execute(*args, **kwargs)  # type: ignore
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Mateo-drr\AppData\Local\miniconda3\Lib\site-packages\wandb\vendor\gql-0.2.0\wandb_gql\client.py", line 52, in execute
    result = self._get_result(document, *args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Mateo-drr\AppData\Local\miniconda3\Lib\site-packages\wandb\vendor\gql-0.2.0\wandb_gql\client.py", line 60, in _get_result
    return self.transport.execute(document, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Mateo-drr\AppData\Local\miniconda3\Lib\site-packages\wandb\sdk\lib\gql_request.py", line 59, in execute
    request.raise_for_status()
  File "C:\Users\Mateo-drr\AppData\Local\miniconda3\Lib\site-packages\requests\models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://api.wandb.ai/graphql

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Mateo-drr\AppData\Local\miniconda3\Lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Mateo-drr\AppData\Local\miniconda3\Lib\site-packages\wandb\filesync\step_upload.py", line 288, in run_and_notify
    self._do_upload_sync(event)
  File "C:\Users\Mateo-drr\AppData\Local\miniconda3\Lib\site-packages\wandb\filesync\step_upload.py", line 330, in _do_upload_sync
    job.run()
  File "C:\Users\Mateo-drr\AppData\Local\miniconda3\Lib\site-packages\wandb\filesync\upload_job.py", line 57, in run
    self.push()
  File "C:\Users\Mateo-drr\AppData\Local\miniconda3\Lib\site-packages\wandb\filesync\upload_job.py", line 106, in push
    _, upload_headers, result = self._api.upload_urls(project, [self.save_name])
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Mateo-drr\AppData\Local\miniconda3\Lib\site-packages\wandb\apis\normalize.py", line 73, in wrapper
    raise err
  File "C:\Users\Mateo-drr\AppData\Local\miniconda3\Lib\site-packages\wandb\apis\normalize.py", line 41, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Mateo-drr\AppData\Local\miniconda3\Lib\site-packages\wandb\sdk\internal\internal_api.py", line 2380, in upload_urls
    query_result = self.gql(
                   ^^^^^^^^^
  File "C:\Users\Mateo-drr\AppData\Local\miniconda3\Lib\site-packages\wandb\sdk\internal\internal_api.py", line 341, in gql
    ret = self._retry_gql(
          ^^^^^^^^^^^^^^^^
  File "C:\Users\Mateo-drr\AppData\Local\miniconda3\Lib\site-packages\wandb\sdk\lib\retry.py", line 147, in __call__
    retry_timedelta_triggered = check_retry_fn(e)
                                ^^^^^^^^^^^^^^^^^
  File "C:\Users\Mateo-drr\AppData\Local\miniconda3\Lib\site-packages\wandb\util.py", line 907, in no_retry_auth
    raise CommError(
wandb.errors.CommError: It appears that you do not have permission to access the requested resource. Please reach out to the project owner to grant you access. If you have the correct permissions, verify that there are no issues with your networking setup.(Error 404: Not Found)
2024-04-05 00:21:45,504 INFO    wandb-upload_1:17468 [upload_job.py:push():131] Uploaded file S:\Cryp-Tor\wandb\run-20240405_002107-qdib93hc\files\config.yaml
2024-04-05 00:21:45,707 INFO    Thread-15 (_thread_body):17468 [sender.py:transition_state():617] send defer: 11
2024-04-05 00:21:45,707 DEBUG   HandlerThread:17468 [handler.py:handle_request():146] handle_request: defer
2024-04-05 00:21:45,707 INFO    HandlerThread:17468 [handler.py:handle_request_defer():172] handle defer: 11
2024-04-05 00:21:45,707 DEBUG   SenderThread:17468 [sender.py:send_request():409] send_request: defer
2024-04-05 00:21:45,707 INFO    SenderThread:17468 [sender.py:send_request_defer():613] handle sender defer: 11
2024-04-05 00:21:45,707 INFO    SenderThread:17468 [file_pusher.py:join():181] waiting for file pusher
2024-04-05 00:21:45,707 INFO    SenderThread:17468 [sender.py:transition_state():617] send defer: 12
2024-04-05 00:21:45,707 DEBUG   HandlerThread:17468 [handler.py:handle_request():146] handle_request: defer
2024-04-05 00:21:45,707 INFO    HandlerThread:17468 [handler.py:handle_request_defer():172] handle defer: 12
2024-04-05 00:21:45,708 DEBUG   SenderThread:17468 [sender.py:send_request():409] send_request: defer
2024-04-05 00:21:45,708 INFO    SenderThread:17468 [sender.py:send_request_defer():613] handle sender defer: 12
2024-04-05 00:21:45,708 INFO    SenderThread:17468 [file_stream.py:finish():595] file stream finish called
2024-04-05 00:21:45,858 INFO    SenderThread:17468 [file_stream.py:finish():599] file stream finish is done
2024-04-05 00:21:45,858 INFO    SenderThread:17468 [sender.py:transition_state():617] send defer: 13
2024-04-05 00:21:45,858 DEBUG   HandlerThread:17468 [handler.py:handle_request():146] handle_request: defer
2024-04-05 00:21:45,858 INFO    HandlerThread:17468 [handler.py:handle_request_defer():172] handle defer: 13
2024-04-05 00:21:45,858 DEBUG   SenderThread:17468 [sender.py:send_request():409] send_request: defer
2024-04-05 00:21:45,858 INFO    SenderThread:17468 [sender.py:send_request_defer():613] handle sender defer: 13
2024-04-05 00:21:45,858 INFO    SenderThread:17468 [sender.py:transition_state():617] send defer: 14
2024-04-05 00:21:45,858 DEBUG   HandlerThread:17468 [handler.py:handle_request():146] handle_request: defer
2024-04-05 00:21:45,858 DEBUG   SenderThread:17468 [sender.py:send():382] send: final
2024-04-05 00:21:45,858 INFO    HandlerThread:17468 [handler.py:handle_request_defer():172] handle defer: 14
2024-04-05 00:21:45,858 DEBUG   SenderThread:17468 [sender.py:send():382] send: footer
2024-04-05 00:21:45,858 DEBUG   SenderThread:17468 [sender.py:send_request():409] send_request: defer
2024-04-05 00:21:45,858 INFO    SenderThread:17468 [sender.py:send_request_defer():613] handle sender defer: 14
2024-04-05 00:21:45,858 DEBUG   HandlerThread:17468 [handler.py:handle_request():146] handle_request: poll_exit
2024-04-05 00:21:45,858 DEBUG   HandlerThread:17468 [handler.py:handle_request():146] handle_request: server_info
2024-04-05 00:21:45,858 DEBUG   HandlerThread:17468 [handler.py:handle_request():146] handle_request: get_summary
2024-04-05 00:21:45,858 DEBUG   HandlerThread:17468 [handler.py:handle_request():146] handle_request: sampled_history
2024-04-05 00:21:45,858 DEBUG   HandlerThread:17468 [handler.py:handle_request():146] handle_request: internal_messages
2024-04-05 00:21:45,858 DEBUG   SenderThread:17468 [sender.py:send_request():409] send_request: poll_exit
2024-04-05 00:21:45,858 DEBUG   SenderThread:17468 [sender.py:send_request():409] send_request: server_info
2024-04-05 00:21:45,858 DEBUG   HandlerThread:17468 [handler.py:handle_request():146] handle_request: job_info
2024-04-05 00:21:46,016 DEBUG   SenderThread:17468 [sender.py:send_request():409] send_request: job_info
2024-04-05 00:21:46,016 INFO    MainThread:17468 [wandb_run.py:_footer_history_summary_info():3837] rendering history
2024-04-05 00:21:46,016 INFO    MainThread:17468 [wandb_run.py:_footer_history_summary_info():3869] rendering summary
2024-04-05 00:21:46,016 INFO    MainThread:17468 [wandb_run.py:_footer_sync_info():3796] logging synced files
2024-04-05 00:21:46,016 DEBUG   HandlerThread:17468 [handler.py:handle_request():146] handle_request: shutdown
2024-04-05 00:21:46,016 INFO    HandlerThread:17468 [handler.py:finish():866] shutting down handler
2024-04-05 00:21:46,879 INFO    WriterThread:17468 [datastore.py:close():294] close: S:\Cryp-Tor\wandb\run-20240405_002107-qdib93hc\run-qdib93hc.wandb
2024-04-05 00:21:47,035 INFO    SenderThread:17468 [sender.py:finish():1548] shutting down sender
2024-04-05 00:21:47,035 INFO    SenderThread:17468 [file_pusher.py:finish():175] shutting down file pusher
2024-04-05 00:21:47,035 INFO    SenderThread:17468 [file_pusher.py:join():181] waiting for file pusher
